#!/usr/bin/env python3
"""
Analyze speculative decoding logs from llama.cpp server.

Usage:
    python scripts/spec_log_analyze.py <spec_log.jsonl>

The log file is generated by running llama-server with --spec-log-file flag.
"""

import json
import sys
import math
from collections import defaultdict
from typing import List, Dict, Any


def load_logs(filepath: str) -> List[Dict[str, Any]]:
    """Load JSON Lines log file."""
    logs = []
    with open(filepath, 'r') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                logs.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(f"Warning: Failed to parse line {line_num}: {e}", file=sys.stderr)
    return logs


def compute_stats(logs: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Compute statistics from speculation logs."""

    # Overall stats
    total_rounds = 0
    total_drafted = 0
    total_accepted = 0

    # Per-position stats
    position_drafted = defaultdict(int)
    position_accepted = defaultdict(int)
    position_entropy_sum = defaultdict(float)
    position_prob_sum = defaultdict(float)

    # Stop reason distribution
    stop_reasons = defaultdict(int)

    # Acceptance rate distribution
    acceptance_rates = []

    for entry in logs:
        draft = entry.get("draft", {})
        verify = entry.get("verify", {})

        n_drafted = draft.get("n", 0)
        n_accepted = verify.get("n_accepted", 0)

        if n_drafted == 0:
            continue

        total_rounds += 1
        total_drafted += n_drafted
        total_accepted += n_accepted

        # Track stop reason
        stop_reason = draft.get("stop_reason", "unknown")
        stop_reasons[stop_reason] += 1

        # Track acceptance rate for this round
        if n_drafted > 0:
            acceptance_rates.append(n_accepted / n_drafted)

        # Per-position analysis
        for token in draft.get("tokens", []):
            pos = token.get("pos", 0)
            position_drafted[pos] += 1
            position_entropy_sum[pos] += token.get("entropy", 0)
            position_prob_sum[pos] += token.get("p", 0)

        # Mark accepted positions
        for i in range(n_accepted):
            position_accepted[i] += 1

    return {
        "total_rounds": total_rounds,
        "total_drafted": total_drafted,
        "total_accepted": total_accepted,
        "position_drafted": dict(position_drafted),
        "position_accepted": dict(position_accepted),
        "position_entropy_sum": dict(position_entropy_sum),
        "position_prob_sum": dict(position_prob_sum),
        "stop_reasons": dict(stop_reasons),
        "acceptance_rates": acceptance_rates,
    }


def print_histogram(values: List[float], title: str, bins: int = 10):
    """Print a simple ASCII histogram."""
    if not values:
        print(f"  No data for {title}")
        return

    min_val = min(values)
    max_val = max(values)

    if min_val == max_val:
        print(f"  All values are {min_val:.2f}")
        return

    bin_width = (max_val - min_val) / bins
    counts = [0] * bins

    for v in values:
        bin_idx = min(int((v - min_val) / bin_width), bins - 1)
        counts[bin_idx] += 1

    max_count = max(counts) if counts else 1
    bar_width = 40

    print(f"  {title}:")
    for i in range(bins):
        bin_start = min_val + i * bin_width
        bin_end = bin_start + bin_width
        bar_len = int(counts[i] / max_count * bar_width)
        bar = '#' * bar_len
        print(f"  [{bin_start:5.2f}-{bin_end:5.2f}] {bar:<{bar_width}} ({counts[i]})")


def print_report(stats: Dict[str, Any]):
    """Print terminal-based statistics report."""

    print("=" * 70)
    print("SPECULATIVE DECODING LOG ANALYSIS")
    print("=" * 70)

    total_rounds = stats["total_rounds"]
    total_drafted = stats["total_drafted"]
    total_accepted = stats["total_accepted"]

    if total_rounds == 0:
        print("\nNo speculation rounds found in log file.")
        return

    acceptance_rate = total_accepted / total_drafted * 100 if total_drafted > 0 else 0
    avg_drafted = total_drafted / total_rounds
    avg_accepted = total_accepted / total_rounds

    print(f"\nOVERALL STATISTICS")
    print("-" * 70)
    print(f"  Total Rounds:      {total_rounds:>10}")
    print(f"  Total Drafted:     {total_drafted:>10}")
    print(f"  Total Accepted:    {total_accepted:>10}")
    print(f"  Acceptance Rate:   {acceptance_rate:>10.2f}%")
    print(f"  Avg Draft/Round:   {avg_drafted:>10.2f}")
    print(f"  Avg Accept/Round:  {avg_accepted:>10.2f}")

    print(f"\nSTOP REASON DISTRIBUTION")
    print("-" * 70)
    for reason, count in sorted(stats["stop_reasons"].items(), key=lambda x: -x[1]):
        pct = count / total_rounds * 100
        print(f"  {reason:<15} {count:>8} ({pct:5.1f}%)")

    print(f"\nACCEPTANCE RATE DISTRIBUTION")
    print("-" * 70)
    print_histogram(stats["acceptance_rates"], "Rate per round", bins=10)

    print(f"\nPOSITION-WISE ANALYSIS")
    print("-" * 70)
    print(f"{'Pos':<5} {'Drafted':<10} {'Accepted':<10} {'Rate %':<10} {'Avg Entropy':<12} {'Avg Prob':<10}")
    print("-" * 70)

    positions = sorted(stats["position_drafted"].keys())
    for pos in positions:
        drafted = stats["position_drafted"].get(pos, 0)
        accepted = stats["position_accepted"].get(pos, 0)
        rate = (accepted / drafted * 100) if drafted > 0 else 0
        avg_entropy = stats["position_entropy_sum"].get(pos, 0) / drafted if drafted > 0 else 0
        avg_prob = stats["position_prob_sum"].get(pos, 0) / drafted if drafted > 0 else 0

        print(f"{pos:<5} {drafted:<10} {accepted:<10} {rate:<10.2f} {avg_entropy:<12.4f} {avg_prob:<10.4f}")

    # Print position acceptance trend
    if len(positions) > 1:
        print(f"\nPOSITION ACCEPTANCE TREND")
        print("-" * 70)
        max_pos = max(positions)
        for pos in positions:
            drafted = stats["position_drafted"].get(pos, 0)
            accepted = stats["position_accepted"].get(pos, 0)
            rate = (accepted / drafted * 100) if drafted > 0 else 0
            bar_len = int(rate / 100 * 50)
            bar = '#' * bar_len
            print(f"  Pos {pos:>2}: {bar:<50} {rate:5.1f}%")

    print("=" * 70)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <spec_log.jsonl>")
        print("\nThis tool analyzes speculation logs generated by llama-server")
        print("with the --spec-log-file flag.")
        sys.exit(1)

    filepath = sys.argv[1]

    try:
        logs = load_logs(filepath)
    except FileNotFoundError:
        print(f"Error: File not found: {filepath}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Loaded {len(logs)} log entries from {filepath}")

    stats = compute_stats(logs)
    print_report(stats)


if __name__ == "__main__":
    main()
